### ISSUE TITLE
Recyclerview/Listview example

### ISSUE THREAD

**Issue by rkpattanaik** [flipkart-incubator/proteus#102]
Unable to find any example of recyclerview implementation with Proteus. Could you please provide an example of how to write the adapter class with viewholder using Proteus? Any sort of hint would also help.
Thanks.

**Comment by adityasharat** [comment]
Hey @rkpattanaik 
Ideally speaking there should be an [AttributeHandler](https://github.com/flipkart-incubator/proteus/blob/master/proteus-core/src/main/java/com/flipkart/android/proteus/processor/AttributeProcessor.java) for the adapter.

```json
{
  "type": "RecyclerView"
  "adapter": <some configuration>
}
```
where the configuration could be something like this

* for single view type

```json
{
  "type": "TextView",
  "text": "@{data[$index].title}"
}
```

And a little more complex for multiple view types.

**Comment by adityasharat** [comment]
I have created another issue to add a default implementation to proteus #103 
Will try and share a proposed implementation in that issue.

**Comment by rkpattanaik** [comment]
Hi @adityasharat 
Could you please give an example of the AttributeProcessor for Recyclerview?

**Comment by adityasharat** [comment]
@rkpattanaik 

> This is only a reference implementation

checkout [recycler-view-adapter](https://github.com/flipkart-incubator/proteus/tree/recycler-view-adapter) branch for a work in progress example. This implementation supports a single view type, but you can extend it to support multiple view type.

Interesting files

* [RecyclerViewParser](https://github.com/flipkart-incubator/proteus/blob/recycler-view-adapter/recyclerview-v7/src/main/java/com/flipkart/android/proteus/support/v7/widget/RecyclerViewParser.java)
* [SimpleAdapter](https://github.com/flipkart-incubator/proteus/blob/recycler-view-adapter/recyclerview-v7/src/main/java/com/flipkart/android/proteus/support/v7/SimpleAdapter.java)
* [layout.json](https://github.com/flipkart-incubator/proteus/blob/b51a7861ee359c4ed724f5434e0022f4750e2484/data/layout.json)
* [user.json](https://github.com/flipkart-incubator/proteus/blob/b51a7861ee359c4ed724f5434e0022f4750e2484/data/user.json)

Meanwhile, we will continue to work on #103 which may or may not have the above interface.

Closing this issue.
