### ISSUE TITLE
Not able to include proteus library in Android Studio 3.0

### ISSUE THREAD

**Issue by passiondroid** [flipkart-incubator/proteus#105]
After following the steps given in ReadMe.

I am getting below error -

`Unable to resolve dependency for ':app@debug/compileClasspath': Could not resolve com.github.flipkart-incubator:proteus-core:5.0.0-rc11. Open File Show Details

![screen shot 2017-11-15 at 2 40 01 pm](https://user-images.githubusercontent.com/1834030/32827706-17fa7e1c-ca13-11e7-9080-7f6cfcd3674c.png)
`

**Comment by passiondroid** [comment]
Below app level build.gradle

```
apply plugin: 'com.android.application'

android {
    compileSdkVersion 26
    defaultConfig {
        applicationId "com.app.sample.proteus"
        minSdkVersion 15
        targetSdkVersion 26
        versionCode 1
        versionName "1.0"
        testInstrumentationRunner "android.support.test.runner.AndroidJUnitRunner"
    }
    buildTypes {
        release {
            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android.txt'), 'proguard-rules.pro'
        }
    }
}

dependencies {
    implementation fileTree(dir: 'libs', include: ['*.jar'])
    implementation 'com.android.support:appcompat-v7:26.1.0'
    implementation 'com.android.support.constraint:constraint-layout:1.0.2'
    implementation 'com.github.flipkart-incubator:proteus-core:5.0.0-rc11@aar'
    implementation 'com.github.flipkart-incubator:gson-adapter:5.0.0-rc11@aar'
    testImplementation 'junit:junit:4.12'
    androidTestImplementation 'com.android.support.test:runner:1.0.1'
    androidTestImplementation 'com.android.support.test.espresso:espresso-core:3.0.1'
}

```

**Comment by adityasharat** [comment]
The library hasn't been migrated to android studio 3.0 yet. You are more than welcome to pick this up and raise a PR else we will pick this up soon.

**Comment by poovarasanvasudevan** [comment]
use
` compile 'com.github.flipkart-incubator:proteus-core:5.0.0-rc11@aar'
 compile'com.github.flipkart-incubator:gson-adapter:5.0.0-rc11@aar'
`

That works fine or use jitpack.io https://jitpack.io/#flipkart-incubator/proteus/5.0.0-rc11

**Comment by nmohideen** [comment]
Detailed error message from Gradle. Looks like an authorization issue on jitpacks.

Unable to resolve dependency for ':app@debug/compileClasspath': Could not resolve com.github.flipkart-incubator:proteus-core:5.0.0-rc12.

Could not resolve com.github.flipkart-incubator:proteus-core:5.0.0-rc12.
Required by:
    project :app
 > Could not resolve com.github.flipkart-incubator:proteus-core:5.0.0-rc12.
    > Could not get resource 'https://jitpack.io/com/github/flipkart-incubator/proteus-core/5.0.0-rc12/proteus-core-5.0.0-rc12.pom'.
          > Could not GET 'https://jitpack.io/com/github/flipkart-incubator/proteus-core/5.0.0-rc12/proteus-core-5.0.0-rc12.pom'. Received status code 401 from server: Unauthorized

**Comment by manishPatwari** [comment]
@passiondroid  Change the dependencies to :
```
    implementation 'com.github.flipkart-incubator.proteus:proteus-core:5.0.0-rc12@aar'
    implementation 'com.github.flipkart-incubator.proteus:gson-adapter:5.0.0-rc12@aar'
```

**Comment by azri92** [comment]
Thanks @manishPatwari! I tried the following first (from the readme):
```
        compile 'com.github.flipkart-incubator:proteus-core:5.0.0-rc12@aar'
        compile 'com.github.flipkart-incubator:gson-adapter:5.0.0-rc12@aar'
```
which didn't work. Then I tried yours and it successfully build.

**Comment by adityasharat** [comment]
Closing this issue. Thanks @manishPatwari

**Comment by sisogit** [comment]
Am getting the below - 
Error: Program type already present: com.flipkart.android.proteus.R

below is the dependencies from the app/build.gradle

```
dependencies {
    implementation fileTree(dir: 'libs', include: ['*.jar'])
    implementation 'com.android.support:appcompat-v7:28.0.0'
    implementation 'com.android.support:design:28.0.0'
    implementation 'com.github.flipkart-incubator.proteus:proteus-core:5.0.0-rc12'
    implementation 'com.github.flipkart-incubator.proteus:gson-adapter:5.0.0-rc12'
    testImplementation 'junit:junit:4.12'
    androidTestImplementation 'com.android.support.test:runner:1.0.2'
    androidTestImplementation 'com.android.support.test.espresso:espresso-core:3.0.2'
}
```
project/build.gradle
```
allprojects {
    repositories {
        maven { url "https://jitpack.io" }
        google()
        jcenter()
    }
}
```
Detailed error - 
gist link - [https://gist.github.com/sisogit/055c93ddc08b1e24c6ae0e4c6f1129f0](url)
SO link - [https://stackoverflow.com/questions/53828150/error-while-including-the-proteus-library-android-support-v7-appcompat-rlayo](url)
