### ISSUE TITLE
How to get text values from several EditTexts in a form?

### ISSUE THREAD

**Issue by rkpattanaik** [flipkart-incubator/proteus#109]
Hi,

This might be a very silly question to ask but I am really unable to figure out a way on how to get the text from an EditText and pass the text to a button click event listener.

For example, I have the below layout json
```javascript
{
  "type": "LinearLayout",
  "layout_height": "match_parent",
  "layout_width": "match_parent",
  "padding": "8dp",
  "orientation": "vertical",
  "children": [
    {
      "type": "EditText",
      "id": "etUsername",
      "layout_height": "wrap_content",
      "layout_width": "match_parent",
      "hint": "Username"
    },
    {
      "type": "EditText",
      "id": "etPassword",
      "layout_height": "wrap_content",
      "layout_width": "match_parent",
      "layout_marginTop": "4dp",
      "hint": "Password"
    },
    {
      "type": "Button",
      "id": "btnLogin",
      "layout_height": "wrap_content",
      "layout_width": "match_parent",
      "layout_marginTop": "4dp",
      "text": "Login",
      "onClick": {
        "action": "apiCall",
        "extras": {
          "endpoint": "www.someapi.com/api/v1/login",
          "method": "POST",
          "body": {
            "username": "",
            "password": ""
          }
        }
      }
    }
  ]
}
```

As you can see, I have a form containing username and password fields and a button. Now I am trying to set the text from **etUsername** and **etPassword** to **username** and **password** fields respectively in the **onClick** event object of the button whenever user clicks the button, but I am unable to figure out how to do that.

It would be a great help if anyone can help me in sorting this out as soon as possible.

Thanks,
Rajesh

**Comment by adityasharat** [comment]
@rkpattanaik this is definitely not a silly question. As of right now, `proteus` supports only one-way binding out-of-the-box, and forms will require two-way bindings. We are working to add forms as a feature, but we are not there yet.

#### If you wish to unblock yourself to continue development here is a suggested solution:

* Make sure you have a reference to the root `ObjectValue` `data` and the root `ProteusView` `container` passed when you called `LayoutInflater. inflate` where you have the `ProteusLayoutInflater.Callback` registered.

* Register the new `AttributeProcessor` for `onChange` event with the `EditText`. ([exmple](https://github.com/flipkart-incubator/proteus/blob/master/design/src/main/java/com/flipkart/android/proteus/support/design/DesignModuleAttributeHelper.java#L56-L107)) and use the `EventProcessor` ([example](https://github.com/flipkart-incubator/proteus/blob/master/proteus-core/src/main/java/com/flipkart/android/proteus/parser/ViewParser.java#L103-L113)).

* In the implementation of the `onChange` attribute set an `TextWatcher ` on the `EditText`.

* In the implementation of the `TextWatcher` get the value of the text, and trigger an event say `onFormInputChange` using `trigger("onFormInputChange", <config>, (ProteusView) view);`. ([example](https://github.com/flipkart-incubator/proteus/blob/master/proteus-core/src/main/java/com/flipkart/android/proteus/parser/ViewParser.java#L109)). Here `config` is an `ObjectValue` which decribes the event, similar to your `onClick -> action -> apiCall` 

* You will get this trigger as a callback in the `ProteusLayoutInflater.Callback.onEvent()` method. ([example](https://github.com/flipkart-incubator/proteus/blob/master/demo/src/main/java/com/flipkart/android/proteus/demo/ProteusActivity.java#L167))

* In the implementation of the `OnEvent` when `event.equals("onFormInputChange")` inject `value` into a data path (say `@{form.data.username}` as on) and call update on the root view.

---

#### How to inject new data into a data path and update the view?

* To assign a value at a data path do `DataBinding.valueOf("some.path").assign(value, data, 0);`
* Then update the `container` by calling `container. getViewManager().update(data)`.

> Also, convert the `onClick` attributes' values to a nested binding. Note the new binding values in `username` and `password` and how the entire `onClick` is also wrapped inside an object with the binding keyword `@` as a key (nested bindings).

```json
{
  "onClick": {
    "@": {
      "action": "apiCall",
      "extras": {
        "endpoint": "www.someapi.com/api/v1/login",
        "method": "POST",
        "body": {
          "username": "@{form.data.username}",
          "password": "@{form.data.password}"
        }
      }
    }
  }
}
```

> Reference schema for *config*

```json
{
  "onChange": {
    "@": {
      "action": "change",
      "changes": [
        {
          "path": "form.data.username",
          "value": "<insert the text value from the TextWatcher before triggering the event>"
        }
      ]
    }
  }
}
```

* Use the `path` and `value` in the `assign()` method in the `onEvent`.

Hope this helps, also we will try and move this into the FAQ.

**Comment by rkpattanaik** [comment]
Thank you very much @adityasharat !!!

I was able to get it right and implemented it successfully. Below is the code.

<code>MyEditTextParser.java</code>
```java
public class MyEditTextParser extends EditTextParser {
    @Override
    protected void addAttributeProcessors() {
        super.addAttributeProcessors();

        addAttributeProcessor(Constants.Attribute.OnChange, new EventProcessor() {
            @Override
            public void setOnEventListener(View view, Value value) {
                ((EditText) view).addTextChangedListener(new TextWatcher() {
                    @Override
                    public void beforeTextChanged(CharSequence charSequence, int i, int i1, int i2) {

                    }

                    @Override
                    public void onTextChanged(CharSequence charSequence, int i, int i1, int i2) {
                        value.getAsObject().addProperty("text", charSequence.toString());
                        trigger(Constants.ViewEvent.OnFormInputChange, value, (ProteusView) view);
                    }

                    @Override
                    public void afterTextChanged(Editable editable) {

                    }
                });
            }
        });
    }
}
```

Inside <code>MainActivity.java</code>
```java
mCallback = new ProteusLayoutInflater.Callback() {
            @NonNull
            @Override
            public ProteusView onUnknownViewType(ProteusContext context, String type, Layout layout, ObjectValue data, int index) {
                return null;
            }

            @Override
            public void onEvent(String event, Value value, ProteusView view) {
                try {
                    if (event.equals(Constants.ViewEvent.OnFormInputChange)) {
                        Binding.DataBinding.valueOf(value.getAsObject().get("path").getAsString()).assign(value.getAsObject().get("text"), mData, 0);
                        mProteusView.getViewManager().update(mData);
                    }

                    if (event.equals(Constants.ViewEvent.OnClick)) {
                        String username = value.getAsObject().get("extras").getAsObject().get("body").getAsObject().get("username").getAsString();
                        Toast.makeText(mProteusContext, "Hi " + username + "!", Toast.LENGTH_SHORT).show();
                    }
                } catch (Exception e) {
                    e.printStackTrace();
                }
            }
        };

mProteusBuilder = new ProteusBuilder()
                .register(RecyclerViewModule.create())
                .register(CardViewModule.create())
                .register(DesignModule.create())
                .register(new MyEditTextParser());

mProteus = mProteusBuilder.build();

mLayout = gson.fromJson(getJsonFromFile(R.raw.activity_login), Layout.class);
        mData = gson.fromJson(getJsonFromFile(R.raw.data_main), ObjectValue.class);

        mProteusView = mProteusLayoutInflater.inflate(mLayout, mData);
```

<code>activity_login.json</code>
```javascript
{
  "type": "LinearLayout",
  "layout_height": "match_parent",
  "layout_width": "match_parent",
  "padding": "8dp",
  "orientation": "vertical",
  "children": [
    {
      "type": "EditText",
      "id": "etUsername",
      "layout_height": "wrap_content",
      "layout_width": "match_parent",
      "hint": "Username",
      "onChange": {
        "path": "data.loginForm.username"
      }
    },
    {
      "type": "EditText",
      "id": "etPassword",
      "layout_height": "wrap_content",
      "layout_width": "match_parent",
      "layout_marginTop": "4dp",
      "hint": "Password",
      "onChange": {
        "path": "data.loginForm.password"
      }
    },
    {
      "type": "Button",
      "id": "btnLogin",
      "layout_height": "wrap_content",
      "layout_width": "match_parent",
      "layout_marginTop": "4dp",
      "text": "Login",
      "onClick": {
        "@" : {
          "action": "apiCall",
          "extras": {
            "endpoint": "www.someapi.com/api/v1/login",
            "method": "POST",
            "body": {
              "username": "@{data.loginForm.username}",
              "password": "@{data.loginForm.password}"
            }
          }
        }
      }
    }
  ]
}
```

**Comment by adityasharat** [comment]
Great, closing this issue.
