### ISSUE TITLE
where can i get the complete set of documentation? 

### ISSUE THREAD

**Issue by ManasiKher** [flipkart-incubator/proteus#110]

**Comment by adityasharat** [comment]
Hey @ManasiKher, sadly the complete documentation or JavaDoc is not hosted publicly and is not complete. We are working on it. If you wish to check it out just check out the proteus and build it; the JavaDoc for each module will be compiled in the `build/docs/javadoc` directory.
You can also check out the [Wiki](https://github.com/flipkart-incubator/proteus/wiki) for some more guides.
You are also most welcome to contribute to the documentation! 😃

**Comment by ManasiKher** [comment]
Hi Aditya,
Sorry to put this one as issue but we are facing problem while adding
validations,click methods  and api calls with jsons. Can you add a short
document about data binding use for the same?

Thanks
Regards
Manasi

**Comment by adityasharat** [comment]
@ManasiKher If it is a question then I urge you post your questions on [StackOverflow](http://stackoverflow.com) using the [proteus](http://stackoverflow.com/questions/tagged/proteus) tag. I will be more than happy to help. Please do share sufficient code/input/expected-output/exceptions etc in the question.
