### ISSUE TITLE
Is there any way I can bind urls of images to imageview, so that they are populated dynamically

### ISSUE THREAD

**Issue by zincle** [flipkart-incubator/proteus#112]

**Comment by adityasharat** [comment]
Urge you post your questions on [StackOverflow](http://stackoverflow.com) using the [proteus](http://stackoverflow.com/questions/tagged/proteus) tag.

You need to register an [ImageLoader](https://github.com/flipkart-incubator/proteus/blob/master/proteus-core/src/main/java/com/flipkart/android/proteus/ProteusLayoutInflater.java#L164) with `Proteus`. Within its callback, you can use Glide, Picasso, or any other image loading library.
