### ISSUE TITLE
srcCompat is not showing vector image

### ISSUE THREAD

**Issue by zincle** [flipkart-incubator/proteus#113]
{
          "type": "LinearLayout",
          "id": "parent",
          "android": "http://schemas.android.com/apk/res/android",
          "tools": "http://schemas.android.com/tools",
          "orientation": "vertical",
          "layout_width": "match_parent",
          "layout_height": "match_parent",
          "background": "@color/white",
          "app": "http://schemas.android.com/apk/res-auto",
          "children": [
            {
              "type": "LinearLayout",
              "layout_width": "match_parent",
              "layout_height": "wrap_content",
              "background": "#2e69b3",
              "orientation": "vertical",
              "paddingLeft": "15dp",
              "paddingRight": "15dp",
              "paddingTop": "15dp",
              "paddingBottom": "15dp",
              "children": [
                {
                  "type": "TextView",
                  "layout_width": "wrap_content",
                  "layout_height": "wrap_content",
                  "gravity": "center",
                  "layout_gravity": "center",
                  "text": "Introducing Trains",
                  "textColor": "@color/white",
                  "textSize": "20sp"
                },
                {
                  "type": "TextView",
                  "layout_width": "wrap_content",
                  "layout_height": "wrap_content",
                  "gravity": "center",
                  "text": "The Hassle-free booking experience. Book IRCTC train tickets, Check\nPNR Status & Live Train Status. ",
                  "textColor": "@color/white",
                  "textSize": "16sp",
                  "layout_gravity": "center",
                  "layout_marginTop": "7dp"
                }
              ]
            },
            {
              "type": "ScrollView",
              "layout_width": "match_parent",
              "layout_height": "wrap_content",
              "children": [
                {
                  "type": "RelativeLayout",
                  "layout_width": "match_parent",
                  "layout_height": "wrap_content",
                  "paddingLeft": "24dp",
                  "paddingRight": "24dp",
                  "paddingTop": "24dp",
                  "children": [
                    {
                      "type": "ImageView",
                      "id": "img1",
                      "layout_width": "24dp",
                      "layout_height": "24dp",
                      "srcCompat": "@drawable/ic_trn_intro_1"
                    },
                    {
                      "type": "TextView",
                      "layout_width": "wrap_content",
                      "layout_height": "wrap_content",
                      "text": "Fastest Booking",
                      "textSize": "17.5sp",
                      "textColor": "#de000000",
                      "layout_marginLeft": "20dp",
                      "layout_toRightOf": "img1"
                    },
                    {
                      "type": "ImageView",
                      "id": "img2",
                      "layout_width": "24dp",
                      "layout_height": "24dp",
                      "srcCompat": "@drawable/ic_trn_intro_2",
                      "layout_below": "img1",
                      "layout_marginTop": "30dp"
                    },
                    {
                      "type": "TextView",
                      "layout_width": "wrap_content",
                      "layout_height": "wrap_content",
                      "text": "Zero Handling Charges",
                      "textSize": "17.5sp",
                      "textColor": "#de000000",
                      "layout_marginLeft": "20dp",
                      "layout_toRightOf": "img2",
                      "layout_alignBottom": "img2",
                      "gravity": "center_vertical"
                    },
                    {
                      "type": "ImageView",
                      "id": "img3",
                      "layout_width": "24dp",
                      "layout_height": "24dp",
                      "srcCompat": "@drawable/ic_trn_intro_3",
                      "layout_below": "img2",
                      "layout_marginTop": "30dp"
                    },
                    {
                      "type": "TextView",
                      "layout_width": "wrap_content",
                      "layout_height": "wrap_content",
                      "text": "goCash Usage",
                      "textSize": "17.5sp",
                      "textColor": "#de000000",
                      "layout_marginLeft": "20dp",
                      "layout_toRightOf": "img3",
                      "layout_alignBottom": "img3"
                    },
                    {
                      "type": "ImageView",
                      "id": "img4",
                      "layout_width": "24dp",
                      "layout_height": "24dp",
                      "srcCompat": "@drawable/ic_trn_intro_4",
                      "layout_below": "img3",
                      "layout_marginTop": "30dp"
                    },
                    {
                      "type": "TextView",
                      "layout_width": "wrap_content",
                      "layout_height": "wrap_content",
                      "text": "Instant Refunds",
                      "textSize": "17.5sp",
                      "textColor": "#de000000",
                      "layout_marginLeft": "20dp",
                      "layout_toRightOf": "img4",
                      "layout_alignBottom": "img4"
                    },
                    {
                      "type": "ImageView",
                      "id": "img5",
                      "layout_width": "24dp",
                      "layout_height": "24dp",
                      "srcCompat": "@drawable/ic_trn_intro_5",
                      "layout_below": "img4",
                      "layout_marginTop": "30dp"
                    },
                    {
                      "type": "TextView",
                      "layout_width": "wrap_content",
                      "layout_height": "wrap_content",
                      "text": "24x7 goCare support",
                      "textSize": "17.5sp",
                      "textColor": "#de000000",
                      "layout_marginLeft": "20dp",
                      "layout_toRightOf": "img5",
                      "layout_alignBottom": "img5"
                    }
                  ]
                }
              ]
            },
            {
              "type": "RelativeLayout",
              "id": "gotItBtn",
              "layout_width": "match_parent",
              "layout_height": "wrap_content",
              "layout_marginTop": "25dp",
              "background": "#00000000",
              "children": [
                {
                  "type": "View",
                  "layout_width": "match_parent",
                  "layout_height": "0.5dp",
                  "background": "#979797"
                },
                {
                  "type": "TextView",
                  "layout_width": "wrap_content",
                  "layout_height": "wrap_content",
                  "text": "GOT IT",
                  "textSize": "16sp",
                  "textColor": "#2e69b3",
                  "layout_alignParentRight": "true",
                  "paddingTop": "15dp",
                  "paddingBottom": "15dp",
                  "paddingRight": "25dp"
                }
              ]
            }
          ]
        }

**Comment by adityasharat** [comment]
I believe that `srcCompat` is not a registered attribute handler by default. You can register it yourself to get this working. [here is an example](https://github.com/flipkart-incubator/proteus/blob/master/design/src/main/java/com/flipkart/android/proteus/support/design/DesignModuleAttributeHelper.java#L86-L107)
