### ISSUE TITLE
Migrate to Android X

### ISSUE THREAD

**Issue by adityasharat** [flipkart-incubator/proteus#136]

**Comment by aritrobanerjee93** [comment]
Hi,
Is there a timeline for this issue?
Also is it safe to use this library in a androidx project?

Thanks,
Aritro

**Comment by adityasharat** [comment]
Without the migration I don't think the project would even compile. I can pick this up if it's blocking your development. You are welcome to contribute as well.

**Comment by aritrobanerjee93** [comment]
I was looking at this library for a long while and finally decided to try this out in our app. It would help a lot if you could get this migrated to androidx.

**Comment by adityasharat** [comment]
Let me get back to you with a timeline for this.

**Comment by adityasharat** [comment]
I should be able to pick this before the 18th, barring unforeseen circumstances.

**Comment by adityasharat** [comment]
Fixed by #141. 
Available in `5.0.0-rc15` and `5.0.0`

**Comment by aritrobanerjee93** [comment]
ERROR: Failed to resolve: com.github.flipkart-incubator.proteus:proteus-core:5.0.0-rc15
Show in Project Structure dialog
Affected Modules: app


ERROR: Failed to resolve: com.github.flipkart-incubator.proteus:gson-adapter:5.0.0-rc15
Show in Project Structure dialog
Affected Modules: app

What seems to be the issue here?

**Comment by adityasharat** [comment]
I can only guess. Did you add `jitpack` to the repositories?

```
	repositories {
		...
		maven { url "https://jitpack.io" }
	}

```

**Comment by aritrobanerjee93** [comment]
```
// Top-level build file where you can add configuration options common to all sub-projects/modules.

buildscript {
    repositories {
        google()
        jcenter()
        
    }
    dependencies {
        classpath 'com.android.tools.build:gradle:3.4.0-rc02'

        // NOTE: Do not place your application dependencies here; they belong
        // in the individual module build.gradle files

    }
}

allprojects {
    repositories {
        google()
        jcenter()
        maven { url "https://jitpack.io" }
        
    }
}

task clean(type: Delete) {
    delete rootProject.buildDir
}
```
project level build.gradle

```
apply plugin: 'com.android.application'

android {
    compileSdkVersion 28
    defaultConfig {
        applicationId "com.example.proteus"
        minSdkVersion 28
        targetSdkVersion 28
        versionCode 1
        versionName "1.0"
        testInstrumentationRunner "androidx.test.runner.AndroidJUnitRunner"
    }
    buildTypes {
        release {
            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android-optimize.txt'), 'proguard-rules.pro'
        }
    }
}

dependencies {

    implementation fileTree(dir: 'libs', include: ['*.jar'])
    implementation 'androidx.appcompat:appcompat:1.0.0-beta01'
    implementation 'androidx.constraintlayout:constraintlayout:1.1.3'
    testImplementation 'junit:junit:4.12'
    androidTestImplementation 'androidx.test:runner:1.1.0-alpha4'
    androidTestImplementation 'androidx.test.espresso:espresso-core:3.1.0-alpha4'
    implementation 'com.github.flipkart-incubator.proteus:proteus-core:5.0.0-rc12@aar'
    implementation 'com.github.flipkart-incubator.proteus:gson-adapter:5.0.0-rc12@aar'
}
```

app Level build.gradle

Android Studio Version 3.4 RC2

Is there anything that I am doing wrong here?
I tried with 5.0.0-rc15 and 5.0.0 too.

**Comment by adityasharat** [comment]
@aritrobanerjee93 try [this demo app](https://github.com/adityasharat/proteus-demo) if you want to get up and running quick.
