### ISSUE TITLE
Unable to determine org.gradle.api.plugins.AndroidMav...

### ISSUE THREAD

**Issue by mgood7123** [flipkart-incubator/proteus#137]
Unable to determine org.gradle.api.plugins.AndroidMavenPlugin argument #1: missing parameter value of type interface org.gradle.internal.Factory, or no service of type org.gradle.internal.Factory<org.gradle.logging.LoggingManagerInternal>

partial contents of file /home/AndroidStudioProjects/TWRPKeyboardVersion2/proteus/cardview-v7/build.gradle :
```
apply plugin: 'com.github.dcendents.android-maven'
```

partial contents of file /home/AndroidStudioProjects/TWRPKeyboardVersion2/build.gradle :
```
        classpath 'com.github.dcendents:android-maven-plugin:1.2'
        classpath 'com.jfrog.bintray.gradle:gradle-bintray-plugin:1.2'
```

**Comment by adityasharat** [comment]
I was able to successfully build the project

Android Studio version:

```
Android Studio 3.3.1
Build #AI-182.5107.16.33.5264788, built on January 28, 2019
JRE: 1.8.0_152-release-1248-b01 x86_64
JVM: OpenJDK 64-Bit Server VM by JetBrains s.r.o
macOS 10.14.2
```

Emulator version

```
Android version: 7.0
```

Could you share the Android Studio version, and emulator version. In addition I would urge you to try a fresh checkout.

**Comment by mgood7123** [comment]
> 
> 
> I was able to successfully build the project
> 
> Android Studio version:
> 
> ```
> Android Studio 3.3.1
> Build #AI-182.5107.16.33.5264788, built on January 28, 2019
> JRE: 1.8.0_152-release-1248-b01 x86_64
> JVM: OpenJDK 64-Bit Server VM by JetBrains s.r.o
> macOS 10.14.2
> ```
> 
> Emulator version
> 
> ```
> Android version: 7.0
> ```
> 
> Could you share the Android Studio version, and emulator version. In addition I would urge you to try a fresh checkout.

sais the person that just posts his description in the TITLE tab instead of the DESCRIPTION tab ._.

**Comment by adityasharat** [comment]
Without more details it will be difficult to help. Especially since the build succeeds locally as well as on [travis](https://travis-ci.org/flipkart-incubator/proteus). Closing this issue.
