### ISSUE TITLE
no jar

### ISSUE THREAD

**Issue by mgood7123** [flipkart-incubator/proteus#139]
is it possible to export proteus as a JAR archive, if so could you provide instructions as to how this can be accomplished

**Comment by adityasharat** [comment]
I don't think it is possible to export an Android library as a `jar` file as explained in the answer of [this SO](https://stackoverflow.com/questions/16763090/how-to-export-library-to-jar-in-android-studio) question.

Could you explain why you need to export it as a `jar`?

**Comment by mgood7123** [comment]
> 
> 
> I don't think it is possible to export an Android library as a `jar` file as explained in the answer of [this SO](https://stackoverflow.com/questions/16763090/how-to-export-library-to-jar-in-android-studio) question.
> 
> Could you explain why you need to export it as a `jar`?

nevermind
