### ISSUE TITLE
Help Wanted : ProteusInflateException

### ISSUE THREAD

**Issue by mdathersajjad** [flipkart-incubator/proteus#142]
I am able to run the demo app in my lenovo tablet. I copied the same code to the application that i am developing but it is throwing this exception.

Data is loading from node server and getting parsed also. I just changed the initialization of Proteus in a separate class instead of the main ApplicationClass. 

Gradle version is also the same: gradle-4.10.1

com.flipkart.android.proteus.exceptions.ProteusInflateException: attribute  'children' must be an array of 'Layout' objects

I haven't changed anything in layouts file. 
Please help any pointers will be helpful

**Comment by mdathersajjad** [comment]
Sorry it was my mistake i removed the CircleViewParser and its included in the json. It will be helpful 
if the framework generates appropriate error message. 

Thanks, Your library is awesome

**Comment by adityasharat** [comment]
Will try and add more appropriate error messages. Thank you for reporting.
