### ISSUE TITLE
how to pass data and layout in proteus inflater for simple android app?

### ISSUE THREAD

**Issue by prajktachvn** [flipkart-incubator/proteus#144]
Hi,I am trying integrate proteus in a simple android app with a textview and a button in an activity. I have an issue passing layout and data in proteusinflater.

**Comment by adityasharat** [comment]
Please checkout [this answer on SO](https://stackoverflow.com/questions/56806285/how-is-data-and-layout-passed-in-proteus-layout-inflater/56855887#56855887)
