### ISSUE TITLE
Firebase rest api response cant parse json responses

### ISSUE THREAD

**Issue by ivorsliide** [flipkart-incubator/proteus#147]
So I have try to implement this using firebase database, for building the json, I get same response from a normal rest api client and other from firebase REST API database, but the json response is pretty much the same.

**REST**: application/json
`{"type":"LinearLayout","layout_width":"match_parent","layout_height":"200dp","orientation":"vertical","padding":"16dp","background":"#cccccc"}`

**Firebase**: application/json; charset=utf-8
`{"background":"#cccccc","layout_height":"200dp","layout_width":"match_parent","orientation":"vertical","padding":"16dp","type":"LinearLayout"}`

So this layout cant be parse

**Comment by adityasharat** [comment]
You might need to share some stack traces for why it "can't be parse". 

My best guess?
`"type":LinearLayout"` should be the first property of the JSON. It seems the firebase serialises JSON properties alphabetically. But the [ProteusTypeAdapterFactory#VALUE_TYPE_ADAPTER](https://github.com/flipkart-incubator/proteus/blob/master/gson-adapter/src/main/java/com/flipkart/android/proteus/gson/ProteusTypeAdapterFactory.java#L100) expects `type` to be the first property to be even considered as a layout object (this is a performance optimisation strategy).

Maybe check out [How Data is Ordered](https://firebase.google.com/docs/database/rest/retrieve-data#section-rest-ordered-data) in Firebase.

**Comment by ivorsliide** [comment]
Thank you, Im going to try to intercept the call and add the type hardcoded, Hopefully is just that, thank you!

**Comment by ivorsliide** [comment]
> You might need to share some stack traces for why it "can't be parse".
> 
> My best guess?
> `"type":LinearLayout"` should be the first property of the JSON. It seems the firebase serialises JSON properties alphabetically. But the [ProteusTypeAdapterFactory#VALUE_TYPE_ADAPTER](https://github.com/flipkart-incubator/proteus/blob/master/gson-adapter/src/main/java/com/flipkart/android/proteus/gson/ProteusTypeAdapterFactory.java#L100) expects `type` to be the first property to be even considered as a layout object (this is a performance optimisation strategy).
> 
> Maybe check out [How Data is Ordered](https://firebase.google.com/docs/database/rest/retrieve-data#section-rest-ordered-data) in Firebase.

You right, I see the issue is in the order the Json is served, Could be possible to search for the **type** anytime is found in the [ ProteusTypeAdapterFactory#VALUE_TYPE_ADAPTER](https://github.com/flipkart-incubator/proteus/blob/master/gson-adapter/src/main/java/com/flipkart/android/proteus/gson/ProteusTypeAdapterFactory.java#L100), I cant find any other way, as also the Layout class has final properties and of course cant be parsed, as it need that **CustomTypeAdapter**

**Comment by adityasharat** [comment]
A search for `'type'` would mean parsing the the whole JSON object once; if `'type'` is found parse the JSON object again into a `Layout`.

If there is no way to order the JSON please consider writing your own type adapter factory (similar to [ProteusTypeAdapterFactory](https://github.com/flipkart-incubator/proteus/blob/master/gson-adapter/src/main/java/com/flipkart/android/proteus/gson/ProteusTypeAdapterFactory.java)).

**Comment by ivorsliide** [comment]
Hi one of the solutions Im going for is rather than changing or creating a new **TypeAdapterFactory** is to rename on ProteusConstants '**type**' for '**atype**', so the sorting will make it always at the top. Do you think just changing forking and changing the constant will work straight away?. If so please close the issue 👍

**Comment by ivorsliide** [comment]
I found a solution, to avoid this issue of sorting I made a custom sorter for the JSON, I have made this script that will look for the type node in the JSON and childrens

**ProteusUtils.kt**
```kotlin
   fun sortJson(jsonObject: JsonElement?, gson: Gson): JsonObject {
            val jsonDinal = JsonObject()
            if (jsonObject != null
                    && !jsonObject.isJsonNull
                    && jsonObject.isJsonObject) {
                if (jsonObject.asJsonObject.has(ProteusConstants.TYPE)) {
                    val get = jsonObject.asJsonObject.get(ProteusConstants.TYPE)
                     jsonDinal.addProperty(ProteusConstants.TYPE, get.asString)
                }
                if (jsonObject.asJsonObject.has("children")
                        && jsonObject.asJsonObject.get("children").isJsonArray) {
                    val childrens: JsonArray = jsonObject.asJsonObject.get("children") as JsonArray
                     val listOfNewBornChildrens = JsonArray()
                    childrens.forEach {
                        if (it.isJsonObject) {
                            val sortJson = sortJson(it, gson)
                            listOfNewBornChildrens.add(sortJson)
                         }
                    }
                    jsonDinal.add("children", listOfNewBornChildrens)
                }
                jsonObject.asJsonObject.entrySet().forEach {
                    if (it.key != "children")
                        jsonDinal.add(it.key, it.value)
                }
            }
             return jsonDinal
        }
    }
```

**Comment by chaitan94** [comment]
> But the ProteusTypeAdapterFactory#VALUE_TYPE_ADAPTER expects type to be the first property to be even considered as a layout object (this is a performance optimisation strategy).

@adityasharat Just adding my opinion here. Doesn't this performance optimisation go against JSON spec itself? This doesn't sound ideal to me as practically no JSON store guarantees ordering of keys for objects. I was curious to know if there is any kind plan on considering changing this logic anytime in future, or if this is a hard decision?

**Comment by adityasharat** [comment]
Since proteus is no longer being actively developed, there are no plans to change this.

While I agree that the JSON spec doesn't set any constrains on the ordering of keys, in the same way, the default type adapters of proteus are spec'd to expect `"type"` as the first key to improve performance (sadly, this isn't documented anywhere). 

If the server relies on using a third party JSON store which does not allow custom serialisers then overriding the default type adapter on the client is the way to solve it.
