### ISSUE TITLE
cannot inflate json result from plugin converter proteus (please help)

### ISSUE THREAD

**Issue by hh-gandsoft** [flipkart-incubator/proteus#149]
my opinion inflate proteus didnt recognize type spinner.
error in log android:

Caused by: com.flipkart.android.proteus.exceptions.ProteusInflateException: attribute  'children' must be an array of 'Layout' objects

this the json layout result from converter proteus:
{
  "type": "FrameLayout",
  "android": "http://schemas.android.com/apk/res/android",
  "app": "http://schemas.android.com/apk/res-auto",
  "id": "content_prospect_new_req_person_info",
  "layout_width": "match_parent",
  "layout_height": "match_parent",
  "layout_behavior": "@string/appbar_scrolling_view_behavior",
  "children": [
    {
      "type": "Spinner",
      "id": "spinner",
      "layout_width": "match_parent",
      "layout_height": "wrap_content"
    }
  ]
}

**Comment by shubhamcse** [comment]
I think spinner is not supported by this library. You need to create a pull request for same as mentioned here https://github.com/flipkart-incubator/proteus/wiki/Components

**Comment by thekirankumar** [comment]
Yes, as @shubhamcse mentioned, you will have to create a small parser for adding support to Spinners.
For an e.g do look at [this](https://github.com/flipkart-incubator/proteus/blob/master/proteus-core/src/main/java/com/flipkart/android/proteus/parser/custom/ImageViewParser.java)
