### ISSUE TITLE
How to create RadioButton, Spinner view?

### ISSUE THREAD

**Issue by aryayudha** [flipkart-incubator/proteus#150]
How to create radio button and spinner view?

**Comment by adityasharat** [comment]
I urge you to post your questions on [StackOverflow](http://stackoverflow.com) using the [proteus](http://stackoverflow.com/questions/tagged/proteus) tag. See [CircleViewParser](https://github.com/flipkart-incubator/proteus/blob/master/demo/src/main/java/com/flipkart/android/proteus/demo/CircleViewParser.java) as an example; also checkout how it is registered [here](https://github.com/flipkart-incubator/proteus/blob/master/demo/src/main/java/com/flipkart/android/proteus/demo/api/ProteusManager.java#L61).
