### ISSUE TITLE
minSdk 19 from 16

### ISSUE THREAD

**Issue by BharathMG-ShareChat** [flipkart-incubator/proteus#151]
Hi,

Is there any reason why you guys upgraded minSdk to 19 from 16 in `5.0.0`? Our app targets users from 16 API version. So, not able to use Proteus because of lower minSdk.

**Comment by adityasharat** [comment]
API 16 is being used by only [1.2% of the Android population](https://developer.android.com/about/dashboards); so we bumped it up. Please feel free to raise a PR to drop it to 16.

**Comment by BharathMG-ShareChat** [comment]
Sure! Thanks!
