### ISSUE TITLE
Recyclerview with different item-layout for each index

### ISSUE THREAD

**Issue by prathmeshz** [flipkart-incubator/proteus#153]
how to implement recyclerview which has different UI for item-layout depending on the index. Could you please provide an example.

**Comment by adityasharat** [comment]
You can create a custom view parser for your recycler view and set the appropriate adapter on it as required.
see issue [150](https://github.com/flipkart-incubator/proteus/issues/150) around how to create a custom view parser.

**Comment by shadowTech827** [comment]
Hey @adityasharat,
Can you please let me know how to simply implement a custom adapter and register it with the recycler view?
Is their any proper document around it which I can follow?
