### ISSUE TITLE
How does it know that is a resource if is not in the Resource types?, fails inflating the menu

### ISSUE THREAD

**Issue by ivorsmorenburg** [flipkart-incubator/proteus#159]
https://github.com/flipkart-incubator/proteus/blob/26c535546f770b8fd81d0357cb19c270e575d5c9/design/src/main/java/com/flipkart/android/proteus/support/design/widget/BottomNavigationViewParser.java#L113

**Comment by adityasharat** [comment]
This is determined when the layout is parsed by the AttributeProcessor [here](https://github.com/flipkart-incubator/proteus/blob/26c535546f770b8fd81d0357cb19c270e575d5c9/proteus-core/src/main/java/com/flipkart/android/proteus/processor/AttributeProcessor.java#L85)
