### ISSUE TITLE
Does it have backward compat support?

### ISSUE THREAD

**Issue by mallocanswer** [flipkart-incubator/proteus#160]
Say you add a XXXView in 1.3 and you start to use this in your layout.
How will app (below 1.3) that doesn't have XXXView handle the new layout?

**Comment by adityasharat** [comment]
Proteus would not render that layout and call [ProteusLayoutInflater.Callback#onUnknownViewType](https://github.com/flipkart-incubator/proteus/blob/master/proteus-core/src/main/java/com/flipkart/android/proteus/ProteusLayoutInflater.java#L146) if a callback is set.
