### ISSUE TITLE
Type needs to be first key in Layout JSON.

### ISSUE THREAD

**Issue by Shrish2784** [flipkart-incubator/proteus#164]
Hi,
My backend API was sorting the resonse json keys alphabetically, which led me to find this behaviour.

Below JSON would cause no problems during parsing.

But if the type doesn't stay the very first key in the object, It isn't parsed to a **Layout** object.

```json
{
  "type": "LinearLayout",
  "layout_width": "match_parent",
  "layout_height": "match_parent",
  "orientation": "vertical",
  "children": [
    {
      "type": "ImageView",
      "id": "@+id/bg_image",
      "layout_width": "match_parent",
      "layout_height": "match_parent",
      "layout_gravity": "center",
      "adjustViewBounds": "false",
      "scaleType": "fitXY",
      "src": "@{image}"
    }
  ]
}
```

Objects can have children which is again an array of such layout objects,
those also need to have type key as the very first key.

One such _invalid json_ exmaple: 

```json
{
  "layout_width": "match_parent",
  "type": "LinearLayout",
  "layout_height": "match_parent",
  "orientation": "vertical",
  "children": [
    {
      "id": "@+id/bg_image",
      "layout_width": "match_parent",
      "type": "ImageView",
      "layout_height": "match_parent",
      "layout_gravity": "center",
      "adjustViewBounds": "false",
      "scaleType": "fitXY",
      "src": "@{image}"
    }
  ]
}
```

Considering, That the ordering of JSON keys can be pretty inconsistent on being passed around between different frameworks,
this seems dicey.

PS: It is tricky to even debug this if you don't already know about the `type key needs to be the first key` thing.

Related to : https://github.com/flipkart-incubator/proteus/issues/147

**Comment by adityasharat** [comment]
As suggested in #147, it might be better to implement a custom type adapter; alternatively, since proteus is no longer being actively developed, please feel free to fork the repo and modify the implementation to your needs!
