### ISSUE TITLE
What about Maven and JCenter repository?

### ISSUE THREAD

**Issue by Mahendran-Sakkarai** [flipkart-incubator/proteus#45]
Is there any maven and jcenter repository is available to include this library as dependency?

**Comment by adityasharat** [comment]
We added it to jitpack.
[https://jitpack.io/#flipkart-incubator/proteus/4.0.0-RC1](https://jitpack.io/#flipkart-incubator/proteus/4.0.0-RC1)
please check it out

**Comment by Mahendran-Sakkarai** [comment]
Fine. Thanks. But some times jitpack giving issue with some gradle versions. My suggestion is to create a repo in jcenter and maven.

**Comment by adityasharat** [comment]
Ohh. Sure we can check jCenter or Maven too.
Can you please describe the problem in jitpack so it can be recorded here, before we close this issue ?

**Comment by Mahendran-Sakkarai** [comment]
Currently there is no issue with integrating `porteus` using jitpack. Some times before i got some issue with some other library which is using jitpack. That's what i mentioned in the above comment.
