### ISSUE TITLE
CustomView Support

### ISSUE THREAD

**Issue by poovarasanvasudevan** [flipkart-incubator/proteus#58]
Is custom Views Supported

**Comment by adityasharat** [comment]
Yes @poovarasanvasudevan, you can plug in custom views into proteus. Let me get back to you with a demo app and add documentation in the GitHub repo.

**Comment by adityasharat** [comment]
@poovarasanvasudevan hey man go ahead and [check this out](https://github.com/adityasharat/proteus-demo). Do go through the `readme`.

**Comment by adityasharat** [comment]
Closing this issue.
