### ISSUE TITLE
Getting 404 : ./index.html error while running 'npm start' command

### ISSUE THREAD

**Issue by TakeoffAndroid** [flipkart-incubator/proteus#59]
As mentioned in the usage docs, I am initiating the command 'npm start' into the project root and  **Server running at http://1XX.X.X.X:8080/** , but after sometime getting error like **404 : ./index.html**

**Comment by adityasharat** [comment]
That should not be an issue though.

* Does the server shut down? 
* Does the demo app work correctly?

**Comment by TakeoffAndroid** [comment]
<img width="567" alt="screen shot 2016-11-07 at 1 31 54 pm" src="https://cloud.githubusercontent.com/assets/11768239/20050421/46574730-a4ef-11e6-82d1-17d5a5e2141c.png">

**Comment by TakeoffAndroid** [comment]
@adityasharat I haven't tested demo app. Will check now.

**Comment by TakeoffAndroid** [comment]
![screenshot_20161111-135324](https://cloud.githubusercontent.com/assets/11768239/20050857/b5c1b766-a4f1-11e6-979d-2f7d83fd7984.png)


App is not working working on clicking fab.

**Comment by adityasharat** [comment]
It seems to be working fine. I could only guess now.

* Are you using genymotion or a real device ?

if so please open [ProteusActivity](https://github.com/flipkart-incubator/proteus/blob/master/demo/src/main/java/com/flipkart/android/proteus/demo/ProteusActivity.java)

change `BASE_URL` to

* `http://10.0.3.2:8080/data/` in case of genymotion
* `http://<ip-of-machine>:8080/data/` in case of real device

**Comment by TakeoffAndroid** [comment]
Ok let me check. If i copy, paste the URL in browser. I am getting error '{"error":"File Not Found"}'. The API's aren't exposed in the browser?

**Comment by adityasharat** [comment]
You want to connect to the host machine in this case. In the emulator `10.0.2.2` routes to the host machines localhost. So they will not work in the browser. 

Please refer to [this](http://stackoverflow.com/questions/5806220/how-to-connect-to-my-http-localhost-web-server-from-android-emulator-in-eclips) SO question for more details.

**Are you using genymotion or a real device or Android AVD ?**

**Comment by TakeoffAndroid** [comment]
Thanks. I am using real device.

**Comment by adityasharat** [comment]
If you are using a real machine please change `BASE_URL` to `http://<your-computers-ip>:8080/data/`

**Comment by TakeoffAndroid** [comment]
Yes! It is working in ip with 10.0.2.2 in emulator. But machine ip in real device it is not working. Getting `W/System.err: java.net.ConnectException: Failed to connect to /1XX.X.0.1:8080` exception

**Comment by adityasharat** [comment]
Will check that out and revert back here.

**Comment by TakeoffAndroid** [comment]
Yeah! Thanks a lot.

**Comment by adityasharat** [comment]
@TakeoffAndroid I just tested with a real device and machine.
* `BASE_URL = "http://192.168.1.5:8080/data/"`
* IP address of device `192.168.1.4`

For this to work the device and the machine need to be on the same network. If that is not the case, then:

* Setup your router to forward the request to your machine (If the machine is behind a router)
* Check your machine's firewall settings.

Please close this issue if it was resolved.

**Comment by TakeoffAndroid** [comment]
It worked. @adityasharat Thanks a lot.

**Comment by adityasharat** [comment]
👍
