### ISSUE TITLE
Using Picasso or Glide for image caching

### ISSUE THREAD

**Issue by theashishranjan** [flipkart-incubator/proteus#74]
Amazing work here. Start exploring the proteus and had a quick question.
From the demo I can see that  Bitmaploader is used to download image from a network. I was wondering what needs to be done to use libraries like Picasso or Glide with the network images so caching is handled by them.

**Comment by theashishranjan** [comment]
The solution turned out to be very simple after digging the source code.
Just override `getBitmap` and use Picasso or Glide to load image into the view

Closing the issue.

**Comment by adityasharat** [comment]
😃
