### ISSUE TITLE
Need Help

### ISSUE THREAD

**Issue by poovarasanvasudevan** [flipkart-incubator/proteus#75]
What Exactly **Value** class does in Event
` override fun onEvent(view: ProteusView?, eventType: EventType?, value: Value?) { 
} `

How can i able to get Json fields from Value class

And You examples Says You using Retrofit and Casting all layouts into Layout class , Is Layout class can you used for Casting any Layout

**Comment by adityasharat** [comment]
The value class just holds the `value` assigned to the event handler. [example](https://github.com/flipkart-incubator/proteus/blob/develop/data/layouts.json#L220)

```
        {
              "type": "TextView",
              "data": {
                "tag": "~@{user.tags[$index]}"
              },
              "layout_marginRight": "8dp",
              "layout_height": "32dp",
              "textSize": "12sp",
              "textColor": "@color/colorAccent",
              "text": "~@{tag}",
              "padding": "8dp",
              "gravity": "center",
              "onClick": "~@{tag}"
            }
```

The `onClick` is set to "@{tag}", so in the callback you `value` will whatever `@{tag}` resolves to.

> What is the `Value` class?

It is the same as `JsonElement` from `gson`. You can do `value.isObject()`, `value.getAsObject().get("some-property")` like you do in gson.

> "Layout class , Is Layout class can you used for Casting any Layout" ??

I didn't quite follow this!!!

**Comment by poovarasanvasudevan** [comment]
You are Casting JSON into Layout Class using retrofit in yout example
`
 Call<Layout> callLayout = resources.getLayout();
 layout = callLayout.execute().body();
`
Is Layout class can able to cast any Json Views

**Comment by adityasharat** [comment]
> **No** JSON is not being cast to a `Layout` object and only specific JSON content can be converted to a `Layout` object viz. a proteus layout.

The demo app uses Retrofit with `Gson`, where the instance of Gson has a `TypeAdapterFactory` which reads and writes `Layout` (or all proteus resource) objects from the network.

Check out [ProteusTypeAdapterFactory](https://github.com/flipkart-incubator/proteus/blob/develop/gson-adapter/src/main/java/com/flipkart/android/proteus/gson/ProteusTypeAdapterFactory.java) and its [usage](https://github.com/flipkart-incubator/proteus/blob/develop/demo/src/main/java/com/flipkart/android/proteus/demo/ProteusActivity.java#L176)

**Comment by adityasharat** [comment]
Closing this issue. Please move all questions to SO
